### ISSUE TITLE
Abyssalcraft renderlib incompatibility

### ISSUE THREAD

**Issue by darklysteamgear** [Meldexun/RenderLib#34] opened 2023-09-26 21:01 UTC
**Describe the bug**
The client crashes with a ticking entity exception when a depths ghoul spawns in the world. This only happens when on a server

**Reproducibility**
Issue is consistent. tested with and without render lib installed, and the issue fixes itself after uninstalling render lib on the client.

**To Reproduce**
Steps to reproduce the behavior.
Please keep in mind that I most likely don't know how other mods involved in this issue work. Thus terms like "Go to dimension X" should be explained in more detail because I probably don't know how to do that.
1. Start a server with abyssalcraft installed
2. install renderlib on the clientside alongside abyssalcraft
3. Spawn in the depths ghoul
4. clientside crash

**Versions**
RenderLib: 1.12.2-1.3.3
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): see log

**Hardware**
CPU: 7950X
RAM: 32GB DDR5
GPU: 4070TI
VRAM: 12GB

**Log File**
https://mclo.gs/nrjnlp9

**Comment by Meldexun** [comment] 2024-02-07 20:40
This issue was reported to the AbyssalCraft issue tracker (https://github.com/Shinoow/AbyssalCraft/issues/342) but the reporter of that issue hasn't used RenderLib. I will close this then as it is unlikely to be caused by RenderLib.

**Closed as completed by Meldexun** 2024-02-07 20:40 UTC
Labels: bug, not a bug
