### ISSUE TITLE
Suspicious self time of culling function (lag?)

### ISSUE THREAD

**Issue by Krutoy242** [Meldexun/RenderLib#19] opened 2022-08-29 08:42 UTC
**Describe the bug**

`/sparkc profiler` command [output](https://spark.lucko.me/aG2SXURjeT) strangely high self time for RenderLib functions:

<img src="https://user-images.githubusercontent.com/936618/187158672-7eb4c753-479c-47e7-b560-e6b7ce9d9db6.png" width=400>

This is strange, because i only have 38 mostly vanilla entities loaded:

<img src="https://user-images.githubusercontent.com/936618/187157785-80b00053-df21-41fd-a130-8aea2123b7b3.png" width=400>

**Reproducibility**

There is screenshot of scene where i run this profiler. About 10 FPS

<img src="https://user-images.githubusercontent.com/936618/187159164-d9d0cf9e-18db-4ed9-b9f2-b7a01a62ab06.png" width=400>
<img src="https://user-images.githubusercontent.com/936618/187160091-61bee4cc-d529-45d7-a697-983306d1a52e.png" width=400>

This low FPS thing happen in worlds with many machines. When i fly out of base, FPS restoring. Im playing [`E2E-E`](https://github.com/Krutoy242/Enigmatica2Expert-Extended) modpack.

- [x] I am unable to reproduce this issue consistently.

**Hardware**

- CPU: i5-7400 3GHz
- RAM: 16GB
- GPU: GTX 1050 Ti

**Log File** [debug.log](https://github.com/Meldexun/RenderLib/files/9443012/debug.log)

**Comment by Meldexun** [comment] 2022-08-29 18:07
You can enable `showFrameTimes` in the RenderLib config to view the overhead of EntityCulling.

Since your GPU is not the fastest it might be better to disable `openglBasedCulling` in the EntityCulling config.
(I still appreciate if you could send me a screenshot with `showFrameTimes` and `openglBasedCulling` enabled.)

**Comment by Krutoy242** [comment] 2022-09-17 06:59
There is screenshot with `showFrameTimes`, `openglBasedCulling` enabled.
![image](https://user-images.githubusercontent.com/936618/190844727-a2d06df7-9e9a-4605-85a9-b4a847275a32.png)

Btw, changing `openglBasedCulling` option wont affect FPS much (can't see difference with eyes, maybe need some FPS profiling)

**Comment by Meldexun** [comment] 2022-09-17 23:09
> changing openglBasedCulling option wont affect FPS much (can't see difference with eyes, maybe need some FPS profiling)

This sounds like you just have low FPS in general without EntityCulling/RenderLib being involved. And the pictures show a very open scene thus there is probably not really a lot of performance to gain by installing EntityCulling.

Besides that EntityCulling 1.12.2-6.2.4 should improve the performance of opengl culling.

Because of this I will also close the issue now. If you think there still is an issue with EntityCulling then please test what exactly the problem is for you. For example fill out a table like this:
EntityCulling | FPS
--- | ---
6.2.4 with opengl culling | ?
6.2.4 without opengl culling | ?
Vanilla | ?

**Closed as completed by Meldexun** 2022-09-17 23:09 UTC
Labels: bug, unconfirmed

**Comment by Krutoy242** [comment] 2022-09-24 10:35
Yeah, i test this world with and without EC, and found no noticeable performance changes.
