### ISSUE TITLE
Renderlib + Industrial Upgrade = compatibility?

### ISSUE THREAD

**Issue by Xisdar** [Meldexun/RenderLib#32] opened 2023-08-29 13:17 UTC
The display of Industrial Upgrade wires near the lighthouse beam is broken when the Renderlib mod is present.
- [x ] I reproduced this issue with as few other mods as possible installed.

openGLDebugOutput -> enabled

[Screenshots](https://i.imgur.com/UT2EqaQ.png)
[Log](https://mclo.gs/sTkN0ny)

**Comment by Meldexun** [comment] 2024-02-07 21:23
I don't understand what the issue is. Placing cables near a beacon doesn't seem to cause any issues and I also don't notice anything unusual in the screenshot.

**Comment by Meldexun** [comment] 2024-03-31 11:16
Seems to be an Industrial Upgrade issue that has nothing to do with RenderLib and is fixed in newer Industrial Upgrade releases.

**Closed as completed by Meldexun** 2024-03-31 11:16 UTC
Labels: bug, not a bug
