### ISSUE TITLE
Crashes with Smooth Entity Lights.

### ISSUE THREAD

**Issue by MagmaSlime123** [Meldexun/RenderLib#40] opened 2024-05-01 03:16 UTC
**Describe the bug**
Title.

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [X] I reproduced this issue with as few other mods as possible installed.
- [X] I am unable to reproduce this issue consistently.

**To Reproduce**
Use both mods and make a world. Game crashes.

**Screenshots/Videos**
N/A.

**Versions**
RenderLib: 1.3.4.
Forge: 2860.
Minecraft: 1.12.2.
Other mods (necessary to reproduce the bug): Smooth Entity Lights, RenderLib, and Mixin Bootstrap.

**Hardware**
CPU: AMD 5700X.
RAM: 16 GB.
GPU: RX 580.
VRAM: 8 gigs.

**Log File**
https://pastebin.com/B6gF08yR

**Comment by Meldexun** [comment] 2024-06-12 17:50
Duplicate of #36

**Closed as completed by Meldexun** 2024-06-12 17:50 UTC
Labels: bug, duplicate
