### ISSUE TITLE
Eh, crash again, but now I don't know what causes it.

### ISSUE THREAD

**Issue by Kasia1403** [Meldexun/RenderLib#17] opened 2022-08-23 14:04 UTC
[crash-2022-08-23_15.44.20-client.txt](https://github.com/Meldexun/RenderLib/files/9403192/crash-2022-08-23_15.44.20-client.txt)
[debug.log](https://github.com/Meldexun/RenderLib/files/9403195/debug.log)
[latest.log](https://github.com/Meldexun/RenderLib/files/9403196/latest.log)

**Comment by Meldexun** [comment] 2022-08-23 14:49
Duplicate of #13

**Closed by Meldexun** 2022-08-23 14:49 UTC
