### ISSUE TITLE
[1.12.2] Weird Entity flicker with EntityCulling after updating RenderLib.

### ISSUE THREAD

**Issue by SonicX8000** [Meldexun/RenderLib#11] opened 2022-07-15 07:58 UTC
**Describe the bug**
The entity flickering randomly depending on how you look at it, such as moving your mouse around the entity, moving around the entity, looking at different angles, etc.

**To Reproduce**
1. Place down an entity, preferability one that doesn't move such as an armor stand.
2. Walk around it while looking at it while moving your mouse.
3. At certain points the entity will disappear for a split second & reappear, aka flicker.

**Screenshots/Videos**
![2022-07-15 03-05-31](https://user-images.githubusercontent.com/36653806/179181216-3fb27384-890d-4392-bd37-84220a6cd73e.gif)

**Versions**
RenderLib: 
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 
RenderLib-1.12.2-1.1.1
EntityCulling-1.12.2-6.0.2
HadEnoughItems_1.12.2-4.22.0
!mixinbooter-4.2

**Log File**
N/A

---

*Note*
This didn't occur when using an old version of RenderLib. Before updating I was using `RenderLib-1.12.2-1.0.6`.

**Comment by Meldexun** [comment] 2022-07-15 12:05
Please use the issue template and provide the requested information.

**Comment by SonicX8000** [comment] 2022-07-15 12:11
Edited the OP

**Comment by Meldexun** [comment] 2022-07-15 20:26
Not reproduceable for me.

Did you change anything in the EntityCulling or RenderLib config?
Are you able to reproduce this in a flatworld with only 1 entity loaded?

**Comment by SonicX8000** [comment] 2022-07-15 20:41
Configs for EntityCulling & RenderLib are their defaults, did another test after deleting the contains of my config folder just to have them regen with their defaults.

Yes, it just depends on the angle you're looking at for the mobs to disappear for a split second.
![2022-07-15 15-34-30](https://user-images.githubusercontent.com/36653806/179307352-04972825-078f-41dd-951c-04debdbb80b3.gif)
 It seems to happen if there are more than 4-5 mobs.

Oh... and the modlist when I took the above GIF.

RenderLib-1.12.2-1.1.1
EntityCulling-1.12.2-6.0.2
HadEnoughItems_1.12.2-4.22.0
_MixinBootstrap-1.1.0

**Comment by Meldexun** [comment] 2022-07-30 15:55
This looks like some ID shifting when a mob enters/leaves the FoV.

**Comment by Meldexun** [comment] 2022-07-30 16:05
Are you able to reproduce this with EntityCulling-1.12.2-6.1.0?

**Comment by SonicX8000** [comment] 2022-07-30 20:35
Was able to reproduce with `EntityCulling-1.12.2-6.1.0`.
![2022-07-30 15-33-01](https://user-images.githubusercontent.com/36653806/181995374-ad327fe4-078f-4ea9-9a0a-f1ec493f30a5.gif)

**Comment by Meldexun** [comment] 2022-07-31 16:40
Duplicate of https://github.com/Meldexun/EntityCulling/issues/70

**Closed as completed** 2022-07-31 16:41 UTC
Labels: bug, duplicate
