### ISSUE TITLE
Crashes on startup with BetterWithMods

### ISSUE THREAD

**Issue by Gliese-832-c** [Meldexun/RenderLib#3] opened 2022-05-30 16:08 UTC
**Describe the bug**
The game crashes while launching if you have BetterWithMods installed.

**To Reproduce**
1. Have this mod as well as BWM installed.
2. Launch game.

**Screenshots/Videos**
Not applicable.

**Versions**
RenderLib: 1.12.2-1.0.7
Forge: 14.23.5.2860
Minecraft: 1.12.2 (duh)
Other mods (necessary to reproduce the bug): BetterWithMods 1.12-2.3.24

**Hardware**
CPU: Ryzen 5 2600
RAM: 2x8GB G.Skill Aegis DDR4-3000
GPU: MSI RX 570 Armor OC 8G
VRAM: 8GB

**Log File**
[crash-2022-05-30_18.03.10-client.txt](https://github.com/Meldexun/RenderLib/files/8799648/crash-2022-05-30_18.03.10-client.txt)

**Comment by Meldexun** [comment] 2022-05-30 17:01
Please reproduce the issue with as few mods as possible.

**Comment by Meldexun** [comment] 2022-06-14 13:46
Closing this now because not getting feedback for some time.

**Closed as completed by Meldexun** 2022-06-14 13:46 UTC
Labels: bug, invalid issue format

**Comment by Gliese-832-c** [comment] 2022-06-18 22:04
Hey, just saw this now. I apologize, I've been busy with IRL stuff recently. Is it fine if I just get back to you when I have time to do extensive testing?

**Comment by Meldexun** [comment] 2022-06-22 16:45
sure
