### ISSUE TITLE
Error Spam and Failed to Launch

### ISSUE THREAD

**Issue by reddvilzz** [Meldexun/RenderLib#18] opened 2022-08-25 02:42 UTC
**Describe the bug**
When installing the mod Industrial Upgrade on my modpack with renderlib the minecraft window will flicker, removing it stopped the issue. I've also submit the issue on [their github](https://github.com/ZelGimi/industrialupgrade/issues/111)

**Versions**
RenderLib: 1.1.4
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): Industrial Upgrade 2.3.5

**Hardware**
CPU: Ryzen 5 3600x
RAM: 32GB
GPU: 1070Ti
VRAM: 8

**Log File**
[debug-3.log](https://github.com/Meldexun/RenderLib/files/9420885/debug-3.log)

**Comment by Meldexun** [comment] 2022-08-25 08:46
Please follow the issue template and provide all information that is requested.

**Comment by reddvilzz** [comment] 2022-08-25 10:51
> Please follow the issue template and provide all information that is requested.

Oh sorry,

Here is the log tested on my modpack [gist](https://gist.github.com/reddvilzz/97455c1b5be774bdf2309c369018a861)
and here is another log with only [RenderLib and Industrial Upgrades ](https://gist.github.com/reddvilzz/6a85f34a77b699a9f794ec86f30b209c)

**To Reproduce**
1. Install renderlib with Industrial Upgrades
2. Launch minecraft
3. Crash

**Reproducibility**
- [X ] I reproduced this issue with as few other mods as possible installed.

**Comment by Meldexun** [comment] 2022-08-25 10:59
Duplicate of #13

**Closed as completed by Meldexun** 2022-08-25 10:59 UTC
Labels: bug, unconfirmed
